apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-qixzsqbo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-qixzsqbo:dc54556cca1d17c585f6ce6a9a0a34a49368fc19@sha256:d97aeae42165d7af3c587251d2c5ad04322d69eec5a8e83234451a39e2e71d82
        name: container-image  
